apiVersion: v1
kind: ConfigMap
metadata:
  name: cib-victoriametrics-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  cib-victoriametrics.yaml: |
    apiVersion: 1
    datasources:
      - name: CIB VictoriaMetrics
        uid: cib-vm
        type: prometheus
        access: proxy
        url: http://cib-victoriametrics.security.svc.cluster.local:8428
        isDefault: false
        editable: true
        jsonData:
          timeInterval: 5m
          httpMethod: POST
